version: "3"
services:
  content_parser:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "AWS_ACCESS_KEY_ID=${CP_AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${CP_AWS_SECRET_ACCESS_KEY}"
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: "npm start"

  tester:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
    command: "npm test"
