version: "3"
services:
  content_parser:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
    command: "npm start"

  tester:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./:/usr/src/app"
    command: "npm test"
